from sqlalchemy import Column, Integer, String, Float
from .database import Base

class InputMaster(Base):
    __tablename__ = "input_master"

    autoid = Column(Integer, primary_key=True, index=True)
    nickname = Column(String, index=True)
    nicknameid = Column(Integer)
    agentid = Column(Integer)
    agentname = Column(String)
    countrycode = Column(String, index=True)
    agentactiveflag = Column(String)
    tmpltbusdefnid = Column(Integer)
    btname = Column(String, index=True)
    accountingsystemid = Column(Integer)
    accntg_sys_desc = Column(String)
    currencyid = Column(Integer)
    currency_name = Column(String)
    consolidatedflag = Column(String)
    specializationid = Column(Integer)
    specializationdescription = Column(String)
    specializationcode = Column(String)
    primaryflag = Column(String)
    priorityid = Column(Integer)
    prioritydesc = Column(String)
    ratinginterest = Column(String)
    clientinterest = Column(String)
    activeflg = Column(String, index=True)
    scaleid = Column(Integer)
    insurancennactiveflag = Column(String)
    businesstypeid = Column(Integer)
    nowcombinedwith = Column(String)
    nicknamedesc = Column(String)
    datasrcid = Column(Integer)
    datasrcdesc = Column(String)
    nicknamemonetarydecimalscale = Column(Integer)
    nicknamenonmonetarydecimalscale = Column(Integer)
    nicknameratiodecimalscale = Column(Integer)
    companyclassid = Column(Integer)
    scaledesc = Column(String)
    rated = Column(String)
    combinedreporting = Column(String)
    templatebusid = Column(Integer)
    landingpageurl = Column(String)
    landingpageurltype = Column(String)
    sourcingapproach = Column(String, index=True)
    domain = Column(String)
    countryisocode = Column(String)
    reportlanguagevaration = Column(String)
    restrictedsource = Column(String)
    landingpageurlprioritytype = Column(String)
    isthirdparty = Column(String)
    thirdpartyuse = Column(String)
    priorityflag = Column(String)
    sourceurlid = Column(Integer)
    hashcode = Column(String)
    inserttimestamp = Column(String)
    entrystatus = Column(String, index=True)
    flag = Column(String)
    table_name_ref = Column(String, name="Table name - tbl_report_master_repository")
    solvencyextractionflag = Column(String)
    sla = Column(String)
    statementPriority = Column(String)
    inputorigin = Column(String)
    inputBucketDetails = Column(String, index=True)
    feedflag = Column(String)
    currency_code = Column(String)
    nicknameinactivereasonid = Column(Float)
    mobius_nickname_active_status = Column(String)
    masterparentbatchid = Column(Float)
    reference = Column(String)
    website = Column(String)
    isgroupwebsite = Column(String)
    reportfiletype = Column(String)
    websitelanguage = Column(String)
    examplereportlink = Column(String)
    reportlinksavailableinui = Column(String)
    reportlinksavailableinsourcepagehref = Column(String)
